const currentUser = checkAuth();
if (!currentUser || !(currentUser.role === 'admin' || currentUser.role === 'both')) { window.location.href = 'login.html'; }
document.getElementById('adminName').innerHTML = currentUser.name;

function loadAdminStats() { let stats = getSystemStats(); document.getElementById('adminStatsGrid').innerHTML = `<div class="stat-card"><div class="stat-value">${stats.totalEmployees}</div><div class="stat-label">Сотрудников</div></div><div class="stat-card"><div class="stat-value">${stats.totalReceipts}</div><div class="stat-label">Всего расписок</div></div><div class="stat-card"><div class="stat-value">${stats.todayReceipts}</div><div class="stat-label">Сегодня</div></div>`; }
function loadAdminEmployees() { let emps = getEmployees(); let html = ''; emps.forEach(emp => { let roleText = emp.role==='both'?'Админ+Сотрудник':(emp.role==='manager'?'Руководитель':'Сотрудник'); html += `<tr><td>${emp.name}</td><td>${emp.login}</td><td>${emp.position||'-'}</td><td>${roleText}</td><td>${emp.receiptCount||0}</td><td><span class="status-badge ${emp.isActive?'status-active':'status-inactive'}">${emp.isActive?'Активен':'Неактивен'}</span></td><td><button class="action-btn" onclick="editEmployee('${emp.login}')">✏️</button><button class="action-btn" onclick="deleteEmployeeConfirm('${emp.login}')">🗑️</button></td></tr>`; }); document.getElementById('adminEmployeesList').innerHTML = html; }
function loadAdminSpecialties() { let cfg = getConfig(); let entries = Object.entries(cfg.specialties).sort((a,b)=>(a[1].order||999)-(b[1].order||999)); let html = ''; entries.forEach(([key,data]) => { html += `<tr><td>${data.code}</td><td>${key}</td><td><input type="number" value="${data.order||999}" style="width:70px" onchange="updateSpecialtyOrder('${key.replace(/'/g,"\\'")}', this.value)"></td><td><span class="status-badge ${data.active!==false?'status-active':'status-inactive'}">${data.active!==false?'Активна':'Скрыта'}</span></td><td><button class="action-btn" onclick="toggleSpecialtyAdmin('${key.replace(/'/g,"\\'")}')">${data.active!==false?'🔒':'🔓'}</button><button class="action-btn" onclick="editSpecialtyAdmin('${key.replace(/'/g,"\\'")}')">✏️</button><button class="action-btn" onclick="deleteSpecialtyAdmin('${key.replace(/'/g,"\\'")}')">🗑️</button></td></tr>`; }); document.getElementById('adminSpecialtiesList').innerHTML = html; }
function loadCounters() { let counters = JSON.parse(localStorage.getItem('receipt_system_counters')||'{}'); let cfg = getConfig(); let html = ''; Object.entries(cfg.specialties).forEach(([name,data]) => { let cur = counters[data.code]||0; html += `<tr><td>${data.code}</td><td>${name.substring(0,40)}</td><td>${cur}</td><td><input type="number" id="newCounter_${data.code}" value="${cur}" style="width:80px"></td><td><button class="action-btn" onclick="updateCounter('${data.code}')">Установить</button><button class="action-btn" onclick="resetCounter('${data.code}')">Сбросить</button></td></tr>`; }); document.getElementById('countersList').innerHTML = html; }
window.updateCounter = function(code) { let newVal = parseInt(document.getElementById('newCounter_'+code).value)||0; let counters = JSON.parse(localStorage.getItem('receipt_system_counters')||'{}'); counters[code]=newVal; localStorage.setItem('receipt_system_counters',JSON.stringify(counters)); showToast('Счётчик '+code+' установлен','success'); loadCounters(); };
window.resetCounter = function(code) { if(confirm('Сбросить?')){ let c={}; c[code]=0; let counters=JSON.parse(localStorage.getItem('receipt_system_counters')||'{}'); counters[code]=0; localStorage.setItem('receipt_system_counters',JSON.stringify(counters)); loadCounters(); } };
window.resetAllCountersGlobal = function() { if(confirm('Сбросить все?')){ localStorage.setItem('receipt_system_counters','{}'); loadCounters(); showToast('Все счётчики сброшены','success'); } };
window.openEmployeeModal = function() { document.getElementById('employeeModalTitle').innerText='Добавить сотрудника'; document.getElementById('editLogin').value=''; document.getElementById('empName').value=''; document.getElementById('empLogin').value=''; document.getElementById('empPassword').value=''; document.getElementById('empPosition').value=''; document.getElementById('empPhone').value=''; document.getElementById('empRole').value='employee'; document.getElementById('empStatus').value='true'; document.getElementById('employeeModal').style.display='flex'; };
window.editEmployee = function(login) { let users = getAllUsers(); let emp = users.find(u=>u.login===login); if(!emp) return; document.getElementById('employeeModalTitle').innerText='Редактировать'; document.getElementById('editLogin').value=emp.login; document.getElementById('empName').value=emp.name; document.getElementById('empLogin').value=emp.login; document.getElementById('empPassword').value=''; document.getElementById('empPosition').value=emp.position||''; document.getElementById('empPhone').value=emp.phone||''; document.getElementById('empRole').value=emp.role; document.getElementById('empStatus').value=emp.isActive?'true':'false'; document.getElementById('employeeModal').style.display='flex'; };
window.saveEmployee = function() { let editLogin = document.getElementById('editLogin').value; let login = document.getElementById('empLogin').value; let name = document.getElementById('empName').value; let pass = document.getElementById('empPassword').value; let position = document.getElementById('empPosition').value; let phone = document.getElementById('empPhone').value; let role = document.getElementById('empRole').value; let isActive = document.getElementById('empStatus').value === 'true'; if(!name||!login){ showToast('Заполните поля','error'); return; } let res; if(editLogin) res = updateEmployee(editLogin, { name, position, phone, role, isActive, ...(pass?{password:pass}:{}) }); else { if(!pass){ showToast('Пароль обязателен','error'); return; } res = addEmployee({ login, name, password:pass, position, phone, role }); } if(res.success){ showToast(editLogin?'Обновлён':'Добавлен','success'); closeEmployeeModal(); loadAdminEmployees(); loadAdminStats(); } else showToast(res.error,'error'); };
window.closeEmployeeModal = function() { document.getElementById('employeeModal').style.display='none'; };
window.toggleSpecialtyAdmin = function(key) { let cfg = getConfig(); if(cfg.specialties[key]){ cfg.specialties[key].active = !cfg.specialties[key].active; saveConfig(cfg); loadAdminSpecialties(); showToast('Статус обновлён','success'); } };
window.updateSpecialtyOrder = function(key,order) { let cfg=getConfig(); if(cfg.specialties[key]){ cfg.specialties[key].order=parseInt(order); saveConfig(cfg); loadAdminSpecialties(); } };
window.editSpecialtyAdmin = function(key) { let cfg=getConfig(); let newCode = prompt('Новый код:', cfg.specialties[key].code); if(newCode) { cfg.specialties[key].code=newCode; saveConfig(cfg); loadAdminSpecialties(); } };
window.deleteSpecialtyAdmin = function(key) { if(confirm('Удалить специальность?')){ let cfg=getConfig(); delete cfg.specialties[key]; saveConfig(cfg); loadAdminSpecialties(); } };
window.openSpecialtyModal = function() { let name = prompt('Название специальности:'); if(name){ let code = prompt('Код:'); if(code){ let cfg=getConfig(); cfg.specialties[name]={ code, name:name.split(' ').slice(1).join(' ')||name, active:true, order:99 }; saveConfig(cfg); loadAdminSpecialties(); } } };
function showToast(msg,type) { let t=document.createElement('div'); t.style.cssText='position:fixed;bottom:20px;right:20px;background:var(--bg-card);border-left:4px solid '+(type==='success'?'var(--success)':'var(--danger)')+';padding:12px 20px;border-radius:10px;z-index:9999'; t.innerText=msg; document.body.appendChild(t); setTimeout(()=>t.remove(),3000); }
loadAdminStats(); loadAdminEmployees(); loadAdminSpecialties(); loadCounters();